server:
  port: 9296


spring:
  application:
    name: config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akki9998111/spring-app-config-2024
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
